### ISSUE TITLE
Enable dark mode automatically when the browser's user preference is set to dark mode

### ISSUE THREAD

**Issue by sleepyfran** [sleepyfran/readder#12]
More and more browsers are implementing a "dark mode" preference that allows websites to detect when the user wants the dark mode to be enabled, so they don't have to specify it manually. I recently did a CSS refactor that should make this trivial to implement.

Further reading: https://css-tricks.com/dark-modes-with-css/

**Comment by andreasvirkus** [comment]
🙋‍♂ I'd like to tackle this

**Comment by sleepyfran** [comment]
>🙋‍♂ I'd like to tackle this

@andreasvirkus great to hear! If you have any doubts or want to discuss any technical detail feel free to mention it here 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andreasvirkus** [comment]
I had a hard time getting the dependencies to install locally (on MacOS Catalina) because of some infamous `node-gyp` errors 😞  (with Node `v12.11.1`)... I might just have to downgrade my Node verson to `8.*` something, as some issues under the `node-gyp` library suggest :/

I started working on the code nonetheless - That's what I've added so far - https://github.com/andreasvirkus/readder/blob/feature/theme-preferences/src/view/App.vue#L33-L60

We can use `window.matchMedia` to initially check for the preference as well as add a listener so it's reactive to any changes that happen while the user is on the site!

Btw, I saw that the theme choice is not persisted atm between site visits - would it be OK to save it in localStorage (or a cookie, up to you) for example? If yes, can I do it within this same issue or would you like it to be a separate PR?

**Comment by sleepyfran** [comment]
@andreasvirkus yeah, I remember having the same issues back when I installed the dependencies for the first time, even in Mojave. I don't remember what I did to solve them finally but right now I have _node_ v10.16.3, so that might be the answer hahaha

As of the code it's looking great so far! I'd definitely advice to either call the _CHANGE_THEME_ mutation directly or adding an optional parameter to the current _SWITCH_THEME_ since this will come in handy if we finally decide to implement some kind of persistence; talking of which, I briefly mentioned it in #16, so it's definitely up to you, if you prefer you can work on this feature on its own and then add some persistence in another branch that we can reuse to start implementing the settings or do it all in this PR and we can continue from here once we decide to start working on the settings. The same for _localStorage_ or a _cookie_! 😋

Thanks for the great work!
